### PR TITLE
README: add travis/coveralls badges

### PR DESCRIPTION
**Pull request by rjw57**
We're not a cool project unless we have these in our README.

We could also add in the PyPI badges (below) in as well if we want to go badge-tastic.

### CODE REVIEW

**Comment by adamgreig** [comment]
+1 on adding the PyPI badge as well

**Comment by rjw57** [comment]
I shall do so...

**Comment by adamgreig** [comment]
Thanks. Slightly cheeky PR to put it in but perhaps add a quick note to the readme that you can add the debug setting to the settings file, since we're editing the readme here anyway...

**Comment by rjw57** [comment]
Wilco. (Or, rather, I'll put it in the #25 which adds that bit to the README.)

**Comment by rjw57** [comment]
Oh... except #25 is closed :).

**Comment by adamgreig** [comment]
Yep, I thought it might be nice shortly after closing #25, but since we have this PR open and changing the readme anyway...

**Comment by rjw57** [comment]
I think that merging will work better with a new one. I've opened #26.

**Comment by adamgreig** [comment]
Fair point. Thanks!

**Pull request merged**
