### PR TITLE
Visual verification tool: ascii map

### PR DESCRIPTION
**Pull request by rjw57**
To be merged after #20. The only new commit is 3fdd61b.

This is a silly little tool which can be used to visually verify that the dataset which has been downloaded is sane and being parsed correctly. When run, it generates a little ASCII-art elevation map. If the output looks like the world map then you can have some confidence that the dataset has downloaded correctly.

Sample screenshot:

ruaumoko-elevation

### CODE REVIEW

**Comment by priyeshpatel** [comment]
:+1: This looks great!

**Comment by rjw57** [comment]
Poo :(. That broke the tests. Will push a fix.

**Comment by rjw57** [comment]
Should now be working. Travis proved itself there...

**Comment by danielrichman** [comment]
This is really cool :P

**Pull request merged**
